version: 7.0.{build}

branches:
  only:
    - master

skip_tags: true
skip_commits:
  files:
    - .github/*
    - README.md

max_jobs: 1

image: Visual Studio 2019

clone_folder: c:\projects\SAM

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'

install:
  - git submodule update --init --recursive

configuration:
  - Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build:
  project: SAM.sln
  parallel: true
  verbosity: minimal

before_build:
  - nuget restore
  
after_build:
  - set TZ=GMT
  - git log . > git-log.txt
  - 7z a -r -tzip -mx=9 -x!*/LICENSE.txt SteamAchievementManager-%APPVEYOR_BUILD_VERSION%.zip ./LICENSE.txt ./git-log.txt ./upload/*.exe ./upload/*.dll

artifacts:
  - path: '*-*.zip'
